version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: sidekick_postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d sequence_sidekick"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: sequence
      POSTGRES_DB: sequence_sidekick
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: sidekick_redis
    image: redis:7.2
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-sequence}
    ports:
      - "6380"
    volumes:
      - redis_data:/data
    
  sequence_sidekick:
    build: .
    container_name: server
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
      - PROJECT_ACCESS_KEY=${PROJECT_ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://dev:sequence@postgres:5432/sequence_sidekick?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SEQUENCE_RPC_URL=${SEQUENCE_RPC_URL}
      - BUILDER_API_SECRET_KEY=${BUILDER_API_SECRET_KEY}
      - INDEXER_URL=${INDEXER_URL}
      - SIGNER_TYPE=${SIGNER_TYPE}
      # AWS KMS configs
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_KMS_KEY_ID=${AWS_KMS_KEY_ID}
      # Google KMS configs
      - PROJECT=${PROJECT}
      - LOCATION=${LOCATION}
      - KEY_RING=${KEY_RING}
      - CRYPTO_KEY=${CRYPTO_KEY}
      - CRYPTO_KEY_VERSION=${CRYPTO_KEY_VERSION}
      - NODE_ENV=development
      # Local Signer configs
      - EVM_PRIVATE_KEY=${EVM_PRIVATE_KEY}
      
    command: ["/bin/sh", "-c", "npx prisma migrate reset --force && pnpm prisma migrate dev --name init && npx prisma migrate deploy && pnpm start"]

volumes:
  postgres_data:
  redis_data: