name: Release tag

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log into Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker build and push
        run: |
          docker build --build-arg VERSION=${GITHUB_REF##*/} -t ghcr.io/0xsequence/sidekick:${GITHUB_REF##*/} -t ghcr.io/0xsequence/sidekick:latest .
          docker push ghcr.io/0xsequence/sidekick:${GITHUB_REF##*/}
          docker push ghcr.io/0xsequence/sidekick:latest