# RDS Variables
variable "rds_id" {}
variable "rds_name" {}
variable "rds_engine" {}
variable "rds_engine_version" {}
variable "rds_instance_class" {}
variable "rds_allocated_storage" {}
variable "rds_max_allocated_storage" {}
variable "rds_port" {}
variable "rds_auth_username" {}
variable "rds_auth_password" {}
variable "rds_db_subnet_name" {}
variable "rds_security_group" {}
variable "rds_publicly_accessible" {}
variable "rds_insights_enabled" {}
variable "rds_Storage_encrypted" {}
variable "rds_deletion_protection" {}
variable "rds_parameter_group_name" {}
variable "rds_skip_final_snapshot" {}
