name: CD - Force ECS Deployment

on:
  push:
    branches: [ "wip-aws-infra" ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'testing_cd/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::150734033613:role/GitHubActionsDeployRole
          role-session-name: GitHubActionsCD

      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster sidekick-cluster \
            --service sidekick-service \
            --force-new-deployment